all:
	javac -cp ".;../../../../../../lib/mallet-2.0.8/mallet-2.0.8/lib/mallet.jar;../../../../../../lib/stanford-corenlp-full-2018-10-05/stanford-corenlp-3.9.2.jar;../../../../../../lib/tweety/net.sf.tweety.tweety-full-1.11-with-dependencies.jar;" IanTextAnalyzer.java

try: 
	javac -cp ".:../../../../../../lib/mallet-2.0.8/mallet-2.0.8/lib/mallet.jar:../../../../../../lib/stanford-corenlp-full-2018-10-05/stanford-corenlp-3.9.2.jar:../../../../../../lib/tweety/net.sf.tweety.tweety-full-1.11-with-dependencies.jar" IanTextAnalyzer.java

try: 